### ISSUE TITLE
Using Swin-Transformer V2 as backbone for YOLO

### ISSUE THREAD

**Issue by sarmientoj24** [ChristophReich1996/Swin-Transformer-V2#11]
What neck do you think works with Swin Transformer? Just basic FPN?
Also, is Swin Transformer sensitive to batch size?

**Comment by ChristophReich1996** [comment]
Hi @sarmientoj24, 

The [original paper](https://arxiv.org/pdf/2111.09883.pdf) showed results for object detection, they used a [Cascade Mask R-
CNN](http://openaccess.thecvf.com/content_cvpr_2018/papers/Cai_Cascade_R-CNN_Delving_CVPR_2018_paper.pdf) architecture. So I would suggest starting with a similar architecture. However, I would recommend asking the authors for their suggestions on this. 
Regarding the sensitivity of different batch sizes, I would expect only a small variance between the network's performance for different batch sizes. The Swin Transformer in general does use any "batch-wise" operation such as Batch Normalization. Thus, different batch sizes only affect the optimization process (gradient estimate). For this reason, I would only expect a minor impact on the network's performance. But no guarantee here, since I did not test the network on different batch sizes.

Cheers,
Christoph
